import mongoose from "mongoose";

const userSchema = new mongoose.Schema({
    username : {type: String, required: true, unique: true},  //only need to provide the username email and 
    password : {type: String, required: true},                // password rest all will be generated by the system
    email : {type: String, required: true, unique: true},
    verifyotp : {type: String,default:''},
    verifyOtpExpireAt :{type: Number,default:0},
    isAccountVerified : {type: Boolean, default: false},
    resetPasswordOtp : {type: String, default:''},
    resetPasswordOtpExpireAt : {type: Number, default:0},
})

const usermodal = mongoose.modelNames.user || mongoose.model('users', userSchema);  //will searchfor user model if not found will create a new one

export default usermodal;